-- VisionHub -- 53_lecciones_de_vida.sql
-- Contenido real del libro "52 Lecciones de Vida" (coleccion global de CdP,
-- autor Guillermo Maldonado), cargado desde 52LeccionesDeVida.txt (raiz del
-- repo). Reemplaza los temas provisionales de seed_01 ('Libro X -- Tema Y')
-- por los titulos reales via ON CONFLICT DO UPDATE.
--
-- 1) El limite de tomos (chk_libro_numero) estaba fijado a 1-7; se quita el
--    tope superior para que agregar tomos futuros (14, 15, ...) nunca
--    requiera otra migracion de esquema, solo datos.
-- 2) Se agregan los tomos 8 y 10-13 (contenido real disponible). El tomo 9
--    tambien se crea (activo, sin temas) para no dejar un hueco en la
--    numeracion -- el tomo 5 ya existia igual, tambien sin temas. Ninguno
--    de los dos tiene contenido disponible todavia (decision del owner,
--    2026-07-26): se dejan activos, listos para cuando se consiga el
--    material.
-- 3) Tres lecciones (Vol. 3 #53/#54, Vol. 10 #53) exceden el rango normal
--    1-52 de esa edicion -- se cargan como es_especial=true, numero=NULL
--    (el mismo mecanismo que ya usa el esquema para "Mega Fiesta"/temas
--    fuera de la numeracion estandar, ver chk_tema_numero en 13_calendario.sql).

ALTER TABLE cdp_libro DROP CONSTRAINT chk_libro_numero;
ALTER TABLE cdp_libro ADD CONSTRAINT chk_libro_numero CHECK (numero > 0);

INSERT INTO cdp_libro (numero, nombre, orden) VALUES
  (8, '52 Lecciones de Vida', 8),
  (9, '52 Lecciones de Vida', 9),
  (10, '52 Lecciones de Vida', 10),
  (11, '52 Lecciones de Vida', 11),
  (12, '52 Lecciones de Vida', 12),
  (13, '52 Lecciones de Vida', 13)
ON CONFLICT (numero) WHERE fecha_eliminacion IS NULL DO NOTHING;

-- Temas normales (numero 1-52), uno por volumen. ON CONFLICT reemplaza los
-- nombres provisionales de seed_01 (Libros 1-3, Temas 1-3) por los reales.
INSERT INTO cdp_tema (libro_id, numero, nombre, es_especial, orden)
SELECT l.id, t.numero, t.nombre, t.especial, t.orden
FROM cdp_libro l
JOIN (VALUES
  (1, 1, 'El arrepentimiento', false, 1),
  (1, 2, 'Las cinco vestiduras de José', false, 2),
  (1, 3, 'La autoridad sobre el enemigo', false, 3),
  (1, 4, '¡Cortemos el chisme!', false, 4),
  (1, 5, 'La conversión de Pablo', false, 5),
  (1, 6, 'Cavar pozos hasta encontrar agua', false, 6),
  (1, 7, 'El ataque de un anti-edificador', false, 7),
  (1, 8, 'Cambiar aguas amargas por aguas dulces', false, 8),
  (1, 9, 'Cómo establecer la justicia en un creyente', false, 9),
  (1, 10, 'El propósito de la mujer', false, 10),
  (1, 11, 'Atrapado en el ciclo de ser víctima', false, 11),
  (1, 12, 'Pactos internos o votos secretos', false, 12),
  (1, 13, 'El principio de la siembra y la cosecha', false, 13),
  (1, 14, 'Preparados para la guerra', false, 14),
  (1, 15, 'El nombre de Jesús', false, 15),
  (1, 16, 'Los malos pensamientos', false, 16),
  (1, 17, 'El testimonio vence todo argumento', false, 17),
  (1, 18, 'La abundancia por medio del pacto', false, 18),
  (1, 19, 'Mujer de excelencia', false, 19),
  (1, 20, 'Un llamado a la pureza', false, 20),
  (1, 21, 'Para cualquier lugar menos para atrás', false, 21),
  (1, 22, 'La ley de la expectación', false, 22),
  (1, 23, '¿Qué es edificar?', false, 23),
  (1, 24, '¿Cómo los opositores atacan los cambios en la iglesia?', false, 24),
  (1, 25, 'Cómo honrar al padre y a la madre', false, 25),
  (1, 26, 'Los edificadores y la sanidad', false, 26),
  (1, 27, 'Los componentes fundamentales de la unidad', false, 27),
  (1, 28, 'Cómo vencer el desánimo', false, 28),
  (1, 29, 'Redimidos de la pobreza', false, 29),
  (1, 30, 'El milagro de Naamán', false, 30),
  (1, 31, 'El corazón endurecido', false, 31),
  (1, 32, 'Qué hacer en el día de la adversidad', false, 32),
  (1, 33, 'No deis lugar al diablo', false, 33),
  (1, 34, 'La casa de Dios anhela edificar', false, 34),
  (1, 35, 'Listos para la cosecha', false, 35),
  (1, 36, 'Las demandas de amor de Dios', false, 36),
  (1, 37, 'El celo por la casa de Dios', false, 37),
  (1, 38, 'Conquistando la tierra prometida', false, 38),
  (1, 39, '¿Qué está haciendo Dios hoy?', false, 39),
  (1, 40, 'Los partos en el Espíritu', false, 40),
  (1, 41, 'Cómo vivir en paz', false, 41),
  (1, 42, 'El poder de la honra', false, 42),
  (1, 43, 'Restaurando el altar de Dios', false, 43),
  (1, 44, 'Sufre con gozo', false, 44),
  (1, 45, 'La comunión con el Espíritu Santo', false, 45),
  (1, 46, 'Cómo construir relaciones fuertes', false, 46),
  (1, 47, 'El poder del testimonio', false, 47),
  (1, 48, 'Teme a Dios y paga tus votos', false, 48),
  (1, 49, 'Conquistando la tierra prometida', false, 49),
  (1, 50, 'Navidad: mitos y verdades', false, 50),
  (1, 51, 'La generación entendida en los tiempos', false, 51),
  (1, 52, 'El poder del testimonio', false, 52),
  (2, 1, 'Dios hace cosa nueva', false, 1),
  (2, 2, 'Un encuentro fresco con Dios', false, 2),
  (2, 3, '¿Qué debemos hacer para que Dios nos cambie?', false, 3),
  (2, 4, 'Agentes que Dios usa para cambiarnos', false, 4),
  (2, 5, '¿Qué hago para ser usado por Dios?', false, 5),
  (2, 6, 'Úsame Señor', false, 6),
  (2, 7, 'El pecado', false, 7),
  (2, 8, 'La Tentación', false, 8),
  (2, 9, 'El ayuno vence las tentaciones', false, 9),
  (2, 10, 'El proceso de la tentación', false, 10),
  (2, 11, '¿Por qué debemos congregarnos?', false, 11),
  (2, 12, 'Jehová es mi Pastor', false, 12),
  (2, 13, 'Funciones de Jesús en los cielos', false, 13),
  (2, 14, 'Tres grandes leyes espirituales', false, 14),
  (2, 15, 'El ayuno bíblico', false, 15),
  (2, 16, 'El beso de Judas', false, 16),
  (2, 17, 'La integridad', false, 17),
  (2, 18, 'Victoria sobre el desierto', false, 18),
  (2, 19, 'Siete métodos de Dios para sanar', false, 19),
  (2, 20, 'Tres cosas que contristan al Espíritu Santo', false, 20),
  (2, 21, 'Recuperando lo que el enemigo nos robó', false, 21),
  (2, 22, 'Semillas de prosperidad financiera', false, 22),
  (2, 23, 'Promesas de Dios para usted', false, 23),
  (2, 24, 'La armadura espiritual (1)', false, 24),
  (2, 25, 'La armadura espiritual (2)', false, 25),
  (2, 26, 'La obediencia', false, 26),
  (2, 27, '¿Qué hay después de la muerte?', false, 27),
  (2, 28, 'La cobertura espiritual', false, 28),
  (2, 29, 'Preocupación, ansiedad y afán', false, 29),
  (2, 30, 'La contienda', false, 30),
  (2, 31, 'La fe del grano de mostaza', false, 31),
  (2, 32, 'Los problemas son valiosos', false, 32),
  (2, 33, '¿Cuándo ignorar y cuándo pelear?', false, 33),
  (2, 34, 'La fidelidad de Dios', false, 34),
  (2, 35, 'La fe no probada no puede ser confiada', false, 35),
  (2, 36, 'Orando de común acuerdo', false, 36),
  (2, 37, 'La guerra espiritual', false, 37),
  (2, 38, 'Jesús, el hacedor de milagros', false, 38),
  (2, 39, 'La gracia de dar', false, 39),
  (2, 40, 'Jesús es mi Señor', false, 40),
  (2, 41, 'Compromiso en medio de las pruebas', false, 41),
  (2, 42, 'Escogiendo la voluntad de Dios', false, 42),
  (2, 43, '¿Qué hacer en tiempos de aflicción?', false, 43),
  (2, 44, 'Los hijos de Caín', false, 44),
  (2, 45, '¿Por qué mis necesidades no son suplidas?', false, 45),
  (2, 46, 'La Santa Cena desata poder', false, 46),
  (2, 47, 'Pasando del fracaso a la victoria', false, 47),
  (2, 48, '¿Por qué no prosperamos?', false, 48),
  (2, 49, 'Dios sigue haciendo milagros', false, 49),
  (2, 50, 'La provisión de Dios', false, 50),
  (2, 51, 'Buscad la paz', false, 51),
  (2, 52, '¿Y cómo será esto?', false, 52),
  (3, 1, 'Amando la palabra de Dios', false, 1),
  (3, 2, 'El ayuno bíblico', false, 2),
  (3, 3, 'Beneficios del ayuno', false, 3),
  (3, 4, 'El cordón de tres dobleces', false, 4),
  (3, 5, 'Ley de la siembra y cosecha', false, 5),
  (3, 6, 'La comunicación en el hogar', false, 6),
  (3, 7, 'El matrimonio es un pacto', false, 7),
  (3, 8, 'Cómo compartir el evangelio con el inconverso', false, 8),
  (3, 9, 'Cómo debemos pensar', false, 9),
  (3, 10, 'Cómo recibir su milagro', false, 10),
  (3, 11, 'Dios quiere, puede y está listo', false, 11),
  (3, 12, 'El corazón endurecido o el espíritu adormecido', false, 12),
  (3, 13, 'El poder paralizante de la incredulidad (1)', false, 13),
  (3, 14, 'El poder paralizante de la incredulidad (2)', false, 14),
  (3, 15, 'El poder de la cruz y la resurrección', false, 15),
  (3, 16, 'Qué hacer en el día de la adversidad', false, 16),
  (3, 17, 'Jesús sigue sanando hoy', false, 17),
  (3, 18, 'El propósito de la creación', false, 18),
  (3, 19, 'Principios bíblicos para orar correctamente', false, 19),
  (3, 20, 'Honremos a nuestra madre', false, 20),
  (3, 21, 'El dedo de Dios (1) El propósito del hombre en la mente de Dios', false, 21),
  (3, 22, 'El dedo de Dios (2) Una nueva generación de guerreros', false, 22),
  (3, 23, 'El dedo de Dios (3)', false, 23),
  (3, 24, 'De "nepio" a "guerrero"', false, 24),
  (3, 25, 'El celo por la casa de Dios', false, 25),
  (3, 26, 'Honrando a nuestro Padre', false, 26),
  (3, 27, 'Cómo desatar la fe', false, 27),
  (3, 28, 'Arrepentimiento de obras muertas', false, 28),
  (3, 29, 'Dependencia o independencia', false, 29),
  (3, 30, 'Los partos en el espíritu', false, 30),
  (3, 31, '¿Qué es un paradigma y cómo vencerlo?', false, 31),
  (3, 32, 'Imposición de manos', false, 32),
  (3, 33, 'La comunión íntima con Dios', false, 33),
  (3, 34, 'La casa que Dios anhela edificar', false, 34),
  (3, 35, 'Para cualquier lugar menos para atrás', false, 35),
  (3, 36, 'La doctrina de bautismos', false, 36),
  (3, 37, 'Cómo compartir su testimonio', false, 37),
  (3, 38, 'Qué decir y qué no decir al evangelizar', false, 38),
  (3, 39, 'Conquistando la tierra prometida', false, 39),
  (3, 40, 'El poder de atar y desatar', false, 40),
  (3, 41, 'Cómo recibir sabiduría', false, 41),
  (3, 42, 'La oración: clave para evangelizar', false, 42),
  (3, 43, '¿Cómo orar por el inconverso?', false, 43),
  (3, 44, 'Ganadores de almas', false, 44),
  (3, 45, 'Evangelizando con poder sobrenatural', false, 45),
  (3, 46, 'Desenmascarando al diablo', false, 46),
  (3, 47, 'Cómo ser libres del miedo', false, 47),
  (3, 48, 'La Santa Cena (1)', false, 48),
  (3, 49, 'La Santa Cena (2)', false, 49),
  (3, 50, 'La gratitud toca su corazón', false, 50),
  (3, 51, 'La fe hacia Dios', false, 51),
  (3, 52, 'El servicio y el liderazgo', false, 52),
  (4, 1, 'Hoy comienza una nueva temporada', false, 1),
  (4, 2, 'El ayuno trae rompimiento', false, 2),
  (4, 3, 'Honrando a Dios con nuestras primicias', false, 3),
  (4, 4, 'El Poder del Pacto', false, 4),
  (4, 5, 'El lugar donde oramos', false, 5),
  (4, 6, 'Cómo oír la voz de Dios', false, 6),
  (4, 7, 'El verdadero amor', false, 7),
  (4, 8, 'Amar es una decisión', false, 8),
  (4, 9, 'La integridad', false, 9),
  (4, 10, 'No luchamos contra carne ni sangre', false, 10),
  (4, 11, 'La oración nos da derechos', false, 11),
  (4, 12, 'No podemos servir a dos señores', false, 12),
  (4, 13, 'Rompiendo el silencio', false, 13),
  (4, 14, 'Orando como Jesús', false, 14),
  (4, 15, '¡Quiero ser sano hoy!', false, 15),
  (4, 16, 'El regalo de la cruz', false, 16),
  (4, 17, 'Llenos de poder', false, 17),
  (4, 18, 'Llamados a cosechar', false, 18),
  (4, 19, 'La mujer virtuosa', false, 19),
  (4, 20, 'Dame de beber', false, 20),
  (4, 21, 'Eternidad en el corazón', false, 21),
  (4, 22, 'Fuérzalos a entrar', false, 22),
  (4, 23, '¿Qué lugar ocupa Dios en tu vida?', false, 23),
  (4, 24, 'La paternidad de Dios revelada', false, 24),
  (4, 25, 'La disciplina: un adorno de gracia', false, 25),
  (4, 26, 'Usted no está solo', false, 26),
  (4, 27, 'Los líderes de hoy', false, 27),
  (4, 28, 'Ricos, poderosos y saludables', false, 28),
  (4, 29, 'Llamados a impactar al mundo', false, 29),
  (4, 30, 'El poder de decisión', false, 30),
  (4, 31, '¿Dónde está el atalaya?', false, 31),
  (4, 32, 'Es tiempo de ser transformados', false, 32),
  (4, 33, 'Dios está haciendo cosa nueva', false, 33),
  (4, 34, 'El yelmo de la salvación', false, 34),
  (4, 35, 'El desánimo', false, 35),
  (4, 36, 'Culpable o Inocente', false, 36),
  (4, 37, 'Cambiando nuestra mentalidad', false, 37),
  (4, 38, 'No se rinda, siga haciendo el bien', false, 38),
  (4, 39, 'Venciendo obstáculos', false, 39),
  (4, 40, 'Tentación, persecución y acusación', false, 40),
  (4, 41, 'El poder de la Honra', false, 41),
  (4, 42, 'Tenemos espíritu de conquista', false, 42),
  (4, 43, 'Quítale la máscara al diablo', false, 43),
  (4, 44, 'Esperando lo mejor de Dios', false, 44),
  (4, 45, 'Sáquele jugo al fruto', false, 45),
  (4, 46, 'Capturando el ADN de la casa', false, 46),
  (4, 47, 'No murmure, sea agradecido', false, 47),
  (4, 48, 'No olvide dar gracias', false, 48),
  (4, 49, 'Dios ama al dador alegre', false, 49),
  (4, 50, 'Venciendo la depresión', false, 50),
  (4, 51, 'Mire hacia adelante', false, 51),
  (4, 52, 'Jesús, la razón de la Navidad', false, 52),
  (6, 1, 'Hágase Tu Voluntad', false, 1),
  (6, 2, 'La Intercesión en el Ahora', false, 2),
  (6, 3, 'Tus Primeros Frutos Honran a Dios', false, 3),
  (6, 4, 'El Ayuno como Arma de Guerra', false, 4),
  (6, 5, 'Un Pacto con Dios Trae Abundancia', false, 5),
  (6, 6, 'Tiempo, Temporada y Propósito', false, 6),
  (6, 7, 'Cómo Recibir Osadía', false, 7),
  (6, 8, 'El Amor Sobrenatural de Dios', false, 8),
  (6, 9, 'Cómo Fluir en lo Profético', false, 9),
  (6, 10, 'Libres del Miedo', false, 10),
  (6, 11, 'Desarrollando el Carácter', false, 11),
  (6, 12, 'Cómo Compartir el Evangelio', false, 12),
  (6, 13, 'Sanando el Corazón de Falta de Perdón', false, 13),
  (6, 14, 'El Rey está Vivo', false, 14),
  (6, 15, 'Aprendiendo a Descansar en Dios', false, 15),
  (6, 16, 'Cómo ser Libre del Estrés', false, 16),
  (6, 17, 'El Poder Creativo de Dios', false, 17),
  (6, 18, 'Diseñada por Dios para ser Esposa', false, 18),
  (6, 19, 'El Ministerio de la Liberación', false, 19),
  (6, 20, 'No Pierdas el Filo del Espíritu', false, 20),
  (6, 21, 'Empoderados para Prosperar', false, 21),
  (6, 22, 'Cómo Vencer el Desánimo', false, 22),
  (6, 23, 'Usados por Dios para Obrar Milagros', false, 23),
  (6, 24, 'La Paternidad de Dios', false, 24),
  (6, 25, 'El Padre Nuestro', false, 25),
  (6, 26, 'El Espíritu de Honra', false, 26),
  (6, 27, 'Desenmascarando al diablo y Halloween', false, 27),
  (6, 28, 'Libre de Falta de Perdón', false, 28),
  (6, 29, 'Entrando en el Descanso de Dios', false, 29),
  (6, 30, 'Dad Gracias por Todo', false, 30),
  (6, 31, 'Cómo ser Fructífero y Productivo', false, 31),
  (6, 32, 'Deje de ser víctima', false, 32),
  (6, 33, 'Conociendo al Dios Todopoderoso', false, 33),
  (6, 34, 'Liberación del Espíritu de esta Era', false, 34),
  (6, 35, 'Trabajando la Bendición o la Maldición', false, 35),
  (6, 36, 'El Poder para Hacer Riquezas', false, 36),
  (6, 37, 'La Fidelidad de Dios', false, 37),
  (6, 38, 'Principios de Reino para Prosperar', false, 38),
  (6, 39, 'Necesitamos Morir al "Yo"', false, 39),
  (6, 40, 'Propósitos de la Autoridad Espiritual', false, 40),
  (6, 41, 'Conociendo la Voluntad de Dios', false, 41),
  (6, 42, 'Pasos para ser Libres de Estrés', false, 42),
  (6, 43, 'El Poder del Pensamiento', false, 43),
  (6, 44, 'La Voluntad de Dios es Sanar a Todos', false, 44),
  (6, 45, 'El Campo de Batalla de la Mente', false, 45),
  (6, 46, 'La Navidad y su Significado Bíblico', false, 46),
  (6, 47, 'Venciendo la distracción, el miedo y el desánimo', false, 47),
  (6, 48, 'Tenemos Autoridad Espiritual', false, 48),
  (6, 49, 'Descansando en Dios', false, 49),
  (6, 50, 'El Poder de la Unidad', false, 50),
  (6, 51, 'Restaurando el Altar de Dios', false, 51),
  (6, 52, 'Un Mandato de Fe', false, 52),
  (7, 1, 'Hoy comienza una nueva temporada', false, 1),
  (7, 2, 'Presentando nuestro cuerpo en ayuno', false, 2),
  (7, 3, 'Por qué debemos honrar a Dios', false, 3),
  (7, 4, 'La importancia de nuestra relación con Dios', false, 4),
  (7, 5, 'Necesitamos un avivamiento', false, 5),
  (7, 6, 'Obstáculos para ganar almas', false, 6),
  (7, 7, 'Denuedo sobrenatural', false, 7),
  (7, 8, 'El poder de orar en el espíritu', false, 8),
  (7, 9, 'Ataques a lo sobrenatural', false, 9),
  (7, 10, 'El ministerio de liberación', false, 10),
  (7, 11, 'Cómo mantener su liberación', false, 11),
  (7, 12, 'Tenemos acceso a los misterios de Dios', false, 12),
  (7, 13, 'Evidencias del bautismo con el Espíritu Santo', false, 13),
  (7, 14, 'La revelación de la resurrección', false, 14),
  (7, 15, 'El significado de la Pascua', false, 15),
  (7, 16, 'La lengua que se levanta en juicio', false, 16),
  (7, 17, 'Libre de fortalezas mentales', false, 17),
  (7, 18, 'La maldición de la pobreza', false, 18),
  (7, 19, 'Una madre que ora', false, 19),
  (7, 20, 'No perdamos la pasión por Dios', false, 20),
  (7, 21, 'Ganando almas para Cristo', false, 21),
  (7, 22, 'El mover del Espíritu Santo', false, 22),
  (7, 23, 'Echando fuera el espíritu de temor', false, 23),
  (7, 24, 'El amor incondicional de un padre', false, 24),
  (7, 25, 'El derramamiento del Espíritu Santo', false, 25),
  (7, 26, 'Necesito liberación', false, 26),
  (7, 27, 'El origen de la maldición', false, 27),
  (7, 28, 'La pasión genuina por Dios', false, 28),
  (7, 29, 'Caminando en la dimensión de señales', false, 29),
  (7, 30, '¿Por qué debemos ganar almas?', false, 30),
  (7, 31, 'Comunión con Dios y con los demás', false, 31),
  (7, 32, 'Más allá de la necesidad', false, 32),
  (7, 33, 'Activando nuestra bendición', false, 33),
  (7, 34, 'La llenura continua', false, 34),
  (7, 35, 'Ofrezcamos sacrificios espirituales', false, 35),
  (7, 36, 'Con esperanza de recibir', false, 36),
  (7, 37, 'Un lugar llamado altar', false, 37),
  (7, 38, 'El propósito del testimonio', false, 38),
  (7, 39, 'Manténgase a la expectativa', false, 39),
  (7, 40, 'Siembre en tierra fértil', false, 40),
  (7, 41, 'Conociendo al Espíritu Santo', false, 41),
  (7, 42, 'Sometidos para ejercer autoridad', false, 42),
  (7, 43, 'Satanás padre de mentira', false, 43),
  (7, 44, 'Cómo ser libres de la maldición de pobreza', false, 44),
  (7, 45, '¡Dios lo hará otra vez!', false, 45),
  (7, 46, 'Un encuentro con el Espíritu Santo', false, 46),
  (7, 47, 'Un corazón agradecido', false, 47),
  (7, 48, 'Heme aquí Señor', false, 48),
  (7, 49, 'Seamos lugar de reposo para el Espíritu Santo', false, 49),
  (7, 50, 'El intercambio de la cruz', false, 50),
  (7, 51, '¡Llegó Navidad!', false, 51),
  (7, 52, 'Rompiendo ataduras con el pasado', false, 52),
  (8, 1, 'Propósitos y Beneficios del Ayuno', false, 1),
  (8, 2, 'El Poder de la Honra', false, 2),
  (8, 3, '¿Por qué Debemos Congregarnos en la Iglesia?', false, 3),
  (8, 4, 'Honrando a Dios con Nuestras Primicias', false, 4),
  (8, 5, 'La Bendición del Padre', false, 5),
  (8, 6, 'Tiempo, Temporada y Propósito', false, 6),
  (8, 7, 'El Amor Sobrenatural de Dios', false, 7),
  (8, 8, '¿Qué es el Diezmo?', false, 8),
  (8, 9, 'La Fe de los Últimos Tiempos', false, 9),
  (8, 10, 'Teniendo Relación con Dios', false, 10),
  (8, 11, 'Cómo Reconocer la Casa de Dios', false, 11),
  (8, 12, 'Beneficios de Diezmar y Ofrendar', false, 12),
  (8, 13, 'El Poder de la Cruz y la Resurrección', false, 13),
  (8, 14, 'El Poder del Nombre de Jesús', false, 14),
  (8, 15, 'Paz en Medio de la Crisis', false, 15),
  (8, 16, 'Libres de un Corazón Endurecido', false, 16),
  (8, 17, 'Trabajando la Bendición o la Maldición', false, 17),
  (8, 18, 'La Vida de Oración de Jesús', false, 18),
  (8, 19, 'La Revelación de la Verdadera Adoración', false, 19),
  (8, 20, 'La Paternidad y la Cobertura Espiritual', false, 20),
  (8, 21, 'Las Leyes Financieras del Reino', false, 21),
  (8, 22, 'Un Corazón Conforme al Corazón de Dios', false, 22),
  (8, 23, 'Obteniendo las Promesas de Dios', false, 23),
  (8, 24, 'Honrando a Nuestro Padre', false, 24),
  (8, 25, 'La Ley de la Siembra y la Cosecha', false, 25),
  (8, 26, 'Cómo Oír la Voz de Dios', false, 26),
  (8, 27, 'Conociendo la Voluntad de Dios', false, 27),
  (8, 28, 'La Necesidad de Congregarnos', false, 28),
  (8, 29, 'Principios de Reino para Prosperar', false, 29),
  (8, 30, 'Mi Dios es un Dios de Milagros', false, 30),
  (8, 31, 'Orar es Tener Intimidad con Dios', false, 31),
  (8, 32, 'Encontrando Descanso en Dios', false, 32),
  (8, 33, 'Cómo ser Libre de la Maldición de la Pobreza', false, 33),
  (8, 34, 'Venciendo el Desánimo', false, 34),
  (8, 35, 'Triunfando en la Batalla de la Mente', false, 35),
  (8, 36, 'El Poder del Ayuno', false, 36),
  (8, 37, 'La Necesidad de una Iglesia Sobrenatural', false, 37),
  (8, 38, 'La Semilla que Desata la Cosecha', false, 38),
  (8, 39, 'El Poder del Testimonio', false, 39),
  (8, 40, 'Un Encuentro Sobrenatural con Dios en CAP', false, 40),
  (8, 41, 'Cómo Apasionarnos por la Presencia de Dios', false, 41),
  (8, 42, '¿Cómo ser Libres de Miedo?', false, 42),
  (8, 43, '¿Cómo Desarrollar una Vida Constante de Oración?', false, 43),
  (8, 44, 'Fe para recibir su Milagro', false, 44),
  (8, 45, '¿Cómo ser Libres de Falta de Perdón?', false, 45),
  (8, 46, 'Cómo Reparar el Altar', false, 46),
  (8, 47, 'Un Corazón Agradecido', false, 47),
  (8, 48, 'Los Enemigos de la Fe', false, 48),
  (8, 49, 'Caminando en su Propósito', false, 49),
  (8, 50, 'La Revelación del Padre', false, 50),
  (8, 51, 'Celebrando a Jesús en Navidad', false, 51),
  (8, 52, 'Dios Está Haciendo Algo Nuevo', false, 52),
  (10, 1, 'El ayuno que desata rompimiento', false, 1),
  (10, 2, 'El poder de las primicias', false, 2),
  (10, 3, 'Orando desde el lugar secreto', false, 3),
  (10, 4, '¿A qué iglesia debo ir?', false, 4),
  (10, 5, 'El poder de la bendición', false, 5),
  (10, 6, 'Dios es mi Padre celestial', false, 6),
  (10, 7, 'Amando al pueblo dándole cuidado pastoral', false, 7),
  (10, 8, 'La palabra de Dios es una espada', false, 8),
  (10, 9, 'Jesús, nombre sobre todo nombre', false, 9),
  (10, 10, 'Aprendiendo a oír la voz de Dios', false, 10),
  (10, 11, 'Por qué tener una cobertura espiritual', false, 11),
  (10, 12, 'Vale la pena el proceso', false, 12),
  (10, 13, 'Liberando nuestro corazón de falta de perdón', false, 13),
  (10, 14, 'Nacido para cumplir un propósito', false, 14),
  (10, 15, 'Venciendo a los cuatro enemigos de la fe', false, 15),
  (10, 16, '¡Él ha resucitado!', false, 16),
  (10, 17, 'Rompiendo la maldición de la pobreza', false, 17),
  (10, 18, 'Los secretos del corazón', false, 18),
  (10, 19, 'Comprometidos a una relación con Dios', false, 19),
  (10, 20, 'Transformados por la presencia de Dios', false, 20),
  (10, 21, 'La iglesia sobrenatural de Jesús', false, 21),
  (10, 22, 'Libres de estrés', false, 22),
  (10, 23, 'Cuando la ansiedad toca su puerta', false, 23),
  (10, 24, 'Honrando a nuestro Padre', false, 24),
  (10, 25, 'Aquí ocurren milagros', false, 25),
  (10, 26, '¿Cómo caminar en la bendición y la gracia de Dios?', false, 26),
  (10, 27, 'La paz inquebrantable', false, 27),
  (10, 28, 'La voluntad de Dios es lo mejor para mi vida', false, 28),
  (10, 29, 'Descubriendo la Biblia', false, 29),
  (10, 30, 'Por qué ir a la iglesia', false, 30),
  (10, 31, 'Victoria en su vida mental', false, 31),
  (10, 32, 'El misterio de las lenguas', false, 32),
  (10, 33, 'Las promesas de Dios son sí y amén', false, 33),
  (10, 34, 'Señor enséñanos a orar', false, 34),
  (10, 35, 'Esperando cosechar', false, 35),
  (10, 36, 'Los rompimientos del ayuno', false, 36),
  (10, 37, 'La importancia del Espíritu Santo en nuestra vida', false, 37),
  (10, 38, 'Distracciones de los últimos tiempos', false, 38),
  (10, 39, 'Venciendo los reemplazos de la fe', false, 39),
  (10, 40, '¿Qué esperar durante CAP?', false, 40),
  (10, 41, 'Declararé las poderosas obras de Dios', false, 41),
  (10, 42, 'Cinco claves del reino para prosperar', false, 42),
  (10, 43, 'Venciendo el miedo con amor', false, 43),
  (10, 44, 'Exponiendo las tinieblas de Halloween', false, 44),
  (10, 45, 'La fe grande que impresionó a Jesús', false, 45),
  (10, 46, 'La casa de Dios', false, 46),
  (10, 47, 'El yelmo de la salvación trae esperanza', false, 47),
  (10, 48, 'El poder de dar gracias', false, 48),
  (10, 49, 'La bendición vs. la maldición', false, 49),
  (10, 50, 'El desánimo no tiene cabida en mí', false, 50),
  (10, 51, 'El compromiso en tiempos de crisis', false, 51),
  (10, 52, 'Jesús la razón de la Navidad', false, 52),
  (11, 1, 'El principio divino de lo primero', false, 1),
  (11, 2, 'La relación más importante', false, 2),
  (11, 3, 'El poder espiritual del ayuno', false, 3),
  (11, 4, 'Una nueva temporada de bendiciones', false, 4),
  (11, 5, 'Caminando en acceso divino', false, 5),
  (11, 6, 'Cómo responde Dios a las oraciones', false, 6),
  (11, 7, 'Un amor apasionado por Dios', false, 7),
  (11, 8, 'Triunfando sobre los pensamientos tóxicos', false, 8),
  (11, 9, 'Hablando y moviéndose en fe', false, 9),
  (11, 10, 'Pide lo que quieras en Mi nombre', false, 10),
  (11, 11, 'La cosecha y el sembrador', false, 11),
  (11, 12, 'La iglesia empoderada', false, 12),
  (11, 13, 'El poder del cuerpo y la sangre de Jesús', false, 13),
  (11, 14, 'Caminando por fe', false, 14),
  (11, 15, 'El antídoto para el estrés', false, 15),
  (11, 16, 'Cómo estar en la voluntad de Dios', false, 16),
  (11, 17, 'Descubriendo el propósito de Dios', false, 17),
  (11, 18, 'Claves para acceder a la presencia de Dios', false, 18),
  (11, 19, 'Distraído o enfocado', false, 19),
  (11, 20, 'Conociendo al Espíritu Santo', false, 20),
  (11, 21, 'Los grandes fundamentos de la fe', false, 21),
  (11, 22, 'El mandato bíblico de la iglesia', false, 22),
  (11, 23, 'El poder de liberar', false, 23),
  (11, 24, 'El camino de la honra', false, 24),
  (11, 25, 'El libro más importante que se ha escrito', false, 25),
  (11, 26, 'Redimidos de la maldición', false, 26),
  (11, 27, 'Con Dios todo es posible', false, 27),
  (11, 28, 'Libera tu mente', false, 28),
  (11, 29, 'Obstáculos para que las oraciones sean respondidas', false, 29),
  (11, 30, 'El fuego santo de Dios', false, 30),
  (11, 31, 'Creados para adorar', false, 31),
  (11, 32, 'Cómo habla Dios hoy', false, 32),
  (11, 33, 'La cura para el corazón endurecido', false, 33),
  (11, 34, 'El Señor que sana', false, 34),
  (11, 35, 'Un estilo de vida de oración', false, 35),
  (11, 36, 'Verdades divinas del amor de Dios', false, 36),
  (11, 37, 'Superando los tiempos difíciles', false, 37),
  (11, 38, 'El poder de orar en lenguas', false, 38),
  (11, 39, 'Sé fuerte y valiente', false, 39),
  (11, 40, 'Sé libre en el nombre de Jesús', false, 40),
  (11, 41, 'Venciendo la preocupación, ansiedad y angustia', false, 41),
  (11, 42, 'La oración perseverante trae rompimientos', false, 42),
  (11, 43, 'Rompiendo el ciclo del miedo', false, 43),
  (11, 44, 'Eligiendo la iglesia correcta', false, 44),
  (11, 45, 'Venciendo el desánimo', false, 45),
  (11, 46, 'Comprometidos con Dios completamente', false, 46),
  (11, 47, 'Vivir agradecidos', false, 47),
  (11, 48, 'Las promesas de Dios para ti', false, 48),
  (11, 49, 'Echando fuera la depresión', false, 49),
  (11, 50, 'Estrategias divinas para orar', false, 50),
  (11, 51, 'El regalo más grande de todos', false, 51),
  (11, 52, 'Yo haré cosa nueva', false, 52),
  (12, 1, 'En primer lugar', false, 1),
  (12, 2, 'El ayuno mueve montañas', false, 2),
  (12, 3, 'La oración lo cambia todo', false, 3),
  (12, 4, 'El comienzo de algo nuevo', false, 4),
  (12, 5, 'Una vida de pensamientos victoriosos', false, 5),
  (12, 6, 'El amor que nunca falla', false, 6),
  (12, 7, 'Guardando nuestros corazones', false, 7),
  (12, 8, 'Confiando en Dios en toda circunstancia', false, 8),
  (12, 9, 'La visión de Dios', false, 9),
  (12, 10, 'Siete formas de vencer las dificultades', false, 10),
  (12, 11, 'Fe en tiempos de incertidumbre', false, 11),
  (12, 12, 'La fuerza de congregarnos', false, 12),
  (12, 13, 'Claves para perseverar en la carrera de la fe', false, 13),
  (12, 14, 'La estrategia de la distracción', false, 14),
  (12, 15, 'El Rey resucitado', false, 15),
  (12, 16, 'Mi paz te doy', false, 16),
  (12, 17, 'La Palabra trae prosperidad', false, 17),
  (12, 18, 'Todas las cosas ayudan para bien', false, 18),
  (12, 19, 'Parados sobre las promesas de Dios', false, 19),
  (12, 20, 'Removiendo el poder de la duda', false, 20),
  (12, 21, 'Viviendo con esperanza', false, 21),
  (12, 22, 'El secreto de esperar en Dios', false, 22),
  (12, 23, 'La carrera de obstáculos de la oración', false, 23),
  (12, 24, 'Conociendo a Dios como nuestro Padre', false, 24),
  (12, 25, 'La victoria en nuestra vida diaria', false, 25),
  (12, 26, 'Llamados a compartir nuestra fe', false, 26),
  (12, 27, 'El poder sanador de Dios', false, 27),
  (12, 28, 'Cómo vivir una vida con propósito', false, 28),
  (12, 29, 'El gozo de servir a Dios', false, 29),
  (12, 30, 'Qué buscar en una iglesia', false, 30),
  (12, 31, 'Viviendo con valentía', false, 31),
  (12, 32, 'Formas bíblicas de prosperar', false, 32),
  (12, 33, 'Un Dios misericordioso', false, 33),
  (12, 34, 'Ponte la armadura de Dios', false, 34),
  (12, 35, 'El camino a una vida bendecida', false, 35),
  (12, 36, 'Ayunando con propósito', false, 36),
  (12, 37, 'El modelo de oración de Jesús', false, 37),
  (12, 38, 'El poder de las palabras llenas de fe', false, 38),
  (12, 39, 'Un corazón para Dios', false, 39),
  (12, 40, '¿Qué es CAP y qué expectativa tenemos?', false, 40),
  (12, 41, 'Las promesas de Dios', false, 41),
  (12, 42, 'Vivir comprometidos con Dios', false, 42),
  (12, 43, 'Derrotando a los enemigos mentales de la vida diaria', false, 43),
  (12, 44, 'El Señor de la siembra y la cosecha', false, 44),
  (12, 45, 'Echando fuera los miedos de la vida', false, 45),
  (12, 46, 'Viviendo por fe', false, 46),
  (12, 47, 'Recuerde dar gracias', false, 47),
  (12, 48, 'Donde Dios y el hombre se encuentran', false, 48),
  (12, 49, 'Ganando la batalla sobre la depresión', false, 49),
  (12, 50, 'Una vida libre de falta de perdón', false, 50),
  (12, 51, 'Cristo la esperanza de la Navidad', false, 51),
  (12, 52, 'Reconociendo la fidelidad de Dios', false, 52),
  (13, 1, '¿Quién es Dios?', false, 1),
  (13, 2, 'Dios quiere tener relacion con nosotros', false, 2),
  (13, 3, 'Acercandonos a Dios', false, 3),
  (13, 4, 'La comunión entre hermanos en Cristo', false, 4),
  (13, 5, '¿Tienes una religión o una relación?', false, 5),
  (13, 6, 'Como tener relacion con Dios', false, 6),
  (13, 7, 'Los beneficios de tener una relacion con Dios', false, 7),
  (13, 8, 'Compartiendo el amor de Dios', false, 8),
  (13, 9, '¿Quién es la iglesia de Cristo?', false, 9),
  (13, 10, 'La importancia del companerismo', false, 10),
  (13, 11, '¿Para qué nos congregamos como iglesia?', false, 11),
  (13, 12, 'Nos congregamos para servir a una visión', false, 12),
  (13, 13, 'Unidos en Cristo', false, 13),
  (13, 14, 'Jesús es el Hijo de Dios', false, 14),
  (13, 15, 'Jesús es nuestro Salvador', false, 15),
  (13, 16, 'La resurrección de Jesús', false, 16),
  (13, 17, 'Pasión por las almas', false, 17),
  (13, 18, 'Somos un espiritu en un cuerpo', false, 18),
  (13, 19, 'El estado caído de la humanidad', false, 19),
  (13, 20, 'Buscando identidad en los lugares incorrectos', false, 20),
  (13, 21, 'Jesús nos da identidad de hijos de Dios', false, 21),
  (13, 22, 'Comunión con Dios y con los hermanos', false, 22),
  (13, 23, 'Amar como Dios ama', false, 23),
  (13, 24, 'El amor se da sin reservas', false, 24),
  (13, 25, 'Caracteristicas del amor de Dios', false, 25),
  (13, 26, 'El amor de Dios demostrado', false, 26),
  (13, 27, '¿Por qué tenemos que orar?', false, 27),
  (13, 28, '¿Por qué muchas oraciones no son contestadas?', false, 28),
  (13, 29, 'Orando en el nombre de Jesús', false, 29),
  (13, 30, 'Compartir como hermanos en Cristo', false, 30),
  (13, 31, 'El pecado y sus consecuencias', false, 31),
  (13, 32, 'El arrepentimiento', false, 32),
  (13, 33, '¿De qué tenemos que arrepentirnos?', false, 33),
  (13, 34, '¿Cómo somos perdonados?', false, 34),
  (13, 35, 'Dios nos manda a arrepentirnos', false, 35),
  (13, 36, 'El juicio de Dios', false, 36),
  (13, 37, 'El juicio del creyente', false, 37),
  (13, 38, 'El juicio de los incrédulos', false, 38),
  (13, 39, 'Somos el cuerpo de Cristo', false, 39),
  (13, 40, '¿Existen el cielo y el infierno?', false, 40),
  (13, 41, '¿Qué dice la Biblia acerca del infierno?', false, 41),
  (13, 42, '¿Cómo es el cielo?', false, 42),
  (13, 43, 'Arrebatando almas', false, 43),
  (13, 44, 'Fijando los ojos en Jesús', false, 44),
  (13, 45, 'Dios nunca falla', false, 45),
  (13, 46, 'Ser agradecidos', false, 46),
  (13, 47, 'Gratitud y oracion', false, 47),
  (13, 48, 'Gratitud hacia Dios y los hermanos', false, 48),
  (13, 49, 'El nacimiento sobrenatural de Jesús', false, 49),
  (13, 50, 'La importancia del Salvador', false, 50),
  (13, 51, 'Celebracion de Navidad', false, 51),
  (13, 52, 'Agradecimiento a Dios por Su bondad', false, 52)
) AS t(libro_numero, numero, nombre, especial, orden) ON l.numero = t.libro_numero
WHERE l.fecha_eliminacion IS NULL
ON CONFLICT (libro_id, numero) WHERE iglesia_id IS NULL AND fecha_eliminacion IS NULL
  DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden;

-- Temas especiales (fuera del rango 1-52): numero queda NULL a proposito
-- (chk_tema_numero lo exige), asi que ON CONFLICT no aplica -- se protege
-- la idempotencia con NOT EXISTS en su lugar.
INSERT INTO cdp_tema (libro_id, numero, nombre, es_especial, orden)
SELECT l.id, NULL, t.nombre, true, t.orden
FROM cdp_libro l
JOIN (VALUES
  (3, '¿Cómo será esto?', true, 53),
  (3, 'Navidad: mitos y verdades', true, 54),
  (10, 'Lo nuevo está aquí', true, 53)
) AS t(libro_numero, nombre, especial, orden) ON l.numero = t.libro_numero
WHERE l.fecha_eliminacion IS NULL
  AND NOT EXISTS (
    SELECT 1 FROM cdp_tema ct
    WHERE ct.libro_id = l.id AND ct.es_especial AND ct.nombre = t.nombre AND ct.fecha_eliminacion IS NULL
  );
