-- VisionHub -- KAN-367 (pedido explicito del owner, 2026-09-17):
-- Los tomos 5 y 9 de "52 Lecciones de Vida" existian en cdp_libro pero sin
-- ningun tema cargado (ver 53_lecciones_de_vida.sql, comentario 2 -- se
-- dejaron activos "listos para cuando se consiga el material"). El owner
-- consiguio el contenido real de ambos tomos -- se cargan acá con el mismo
-- patron que el resto de los libros (ON CONFLICT sobre libro_id+numero,
-- por si esto se reaplica).

INSERT INTO cdp_tema (libro_id, numero, nombre, es_especial, orden)
SELECT l.id, t.numero, t.nombre, false, t.numero
FROM cdp_libro l
JOIN (VALUES
  (5, 1, 'Recompensas de la honra'),
  (5, 2, 'Las primicias tienen poder de redención'),
  (5, 3, 'El poder del voto sobrenatural'),
  (5, 4, 'Tres armas poderosas'),
  (5, 5, 'Comisionados por Jesús'),
  (5, 6, 'Misterios del amor sobrenatural'),
  (5, 7, 'Jesús la esperanza viva'),
  (5, 8, 'Cómo edificar una familia fuerte'),
  (5, 9, 'Cortando el chisme'),
  (5, 10, 'La renovación de la mente'),
  (5, 11, 'El divorcio y sus consecuencias'),
  (5, 12, 'Pescando con poder y compasión'),
  (5, 13, 'Experimentando el poder de la resurrección'),
  (5, 14, 'Prácticas sexuales ilícitas'),
  (5, 15, 'Cómo confrontar'),
  (5, 16, 'Desarrollando el temor de Dios'),
  (5, 17, 'Los problemas son valiosos'),
  (5, 18, 'Funciones y roles de la mujer'),
  (5, 19, 'El tabernáculo de David'),
  (5, 20, 'Resistencia y perseverancia'),
  (5, 21, 'Formando nuestro carácter'),
  (5, 22, 'Beneficios de diezmar y ofrendar'),
  (5, 23, 'El principio de ser cabeza'),
  (5, 24, 'El padre corrige y disciplina'),
  (5, 25, 'Del fracaso a la victoria'),
  (5, 26, 'La verdad nos hará libres'),
  (5, 27, 'Liderando con coraje'),
  (5, 28, 'El ciclo de los pensamientos'),
  (5, 29, 'Oración es intimidad con Dios'),
  (5, 30, 'El sexo en el matrimonio'),
  (5, 31, 'La segunda venida de Cristo'),
  (5, 32, 'La oración produce poder'),
  (5, 33, 'La ley del proceso'),
  (5, 34, 'El evangelio del reino y el arrepentimiento'),
  (5, 35, 'Un corazón obediente'),
  (5, 36, 'El poder del compromiso'),
  (5, 37, 'Cuándo ignorar y cuándo pelear'),
  (5, 38, 'Usted tiene poder en Cristo'),
  (5, 39, 'Tentación, persecución y acusación'),
  (5, 40, 'Sanando un corazón ofendido'),
  (5, 41, 'La visión de Dios para las almas'),
  (5, 42, 'Cómo resistir al enemigo'),
  (5, 43, 'Sólo el diablo se disfraza'),
  (5, 44, 'La circuncisión del corazón'),
  (5, 45, 'La unidad en el matrimonio'),
  (5, 46, 'Caminando en gracia sobrenatural'),
  (5, 47, 'El poder de acción de gracias'),
  (5, 48, 'Portadores de la gloria de Dios'),
  (5, 49, 'El compromiso en las pruebas'),
  (5, 50, 'El señorío de Cristo'),
  (5, 51, 'Navidad es celebrar a Jesús'),
  (5, 52, 'Rompiendo paradigmas mentales'),

  (9, 1, 'El ayuno: un arma sobrenatural de poder'),
  (9, 2, 'Honra, la llave que da acceso a las bendiciones de Dios'),
  (9, 3, 'Los beneficios de congregarse en una iglesia'),
  (9, 4, 'La importancia y necesidad de la oración'),
  (9, 5, 'La bendición del Padre tiene poder'),
  (9, 6, 'El poder de la Santa Cena y la sangre de Jesús'),
  (9, 7, 'Jesús: mi gran amor y pasión'),
  (9, 8, 'El dar desata las bendiciones del cielo'),
  (9, 9, 'Distracciones de los últimos tiempos'),
  (9, 10, 'El poder de hablar en lenguas'),
  (9, 11, 'Cualidades importantes de una iglesia'),
  (9, 12, 'La ley financiera del intercambio'),
  (9, 13, 'La oración efectiva produce respuestas'),
  (9, 14, 'Un encuentro fresco con la presencia de Dios'),
  (9, 15, 'La obediencia: llave maestra del favor de Dios'),
  (9, 16, 'Jesús se levantó de los muertos'),
  (9, 17, 'Semillas de sabiduría para prosperar'),
  (9, 18, 'Llaves para entrar al lugar secreto de oración'),
  (9, 19, 'Rompiendo la fortaleza de amargura'),
  (9, 20, 'Habitando juntos en armonía'),
  (9, 21, 'Cómo vencer el desánimo'),
  (9, 22, 'Ganando la batalla de la mente'),
  (9, 23, 'Principios de reino para prosperar'),
  (9, 24, 'Restaurando la honra a Dios'),
  (9, 25, 'Fe sobrenatural en el ahora'),
  (9, 26, 'El propósito de Dios'),
  (9, 27, 'Viviendo en el descanso de Dios'),
  (9, 28, 'Conociendo a Dios como nuestro Padre celestial'),
  (9, 29, 'El poder del pacto sobrenatural'),
  (9, 30, 'Beneficios de la paternidad y la cobertura espiritual'),
  (9, 31, 'El poder de una vida de oración diaria'),
  (9, 32, 'La transformación del corazón'),
  (9, 33, 'Caminando en el poder de nuestra confesión de fe'),
  -- Nota: tal como viene en el material del owner -- parecen 2 títulos
  -- pegados en uno solo. Se carga tal cual; avisar si hay que separarlo.
  (9, 34, 'Importancia de las finanzas en la familia. Encuentros sobrenaturales con Dios por medio de la oración'),
  (9, 35, 'Beneficios y recompensas del ayuno'),
  (9, 36, 'Orando desde una posición de justicia'),
  (9, 37, 'Qué debemos buscar en una iglesia'),
  (9, 38, 'Activando el poder del testimonio'),
  (9, 39, 'Experimentando la gloria de Dios en CAP'),
  (9, 40, 'La necesidad del Espíritu Santo'),
  (9, 41, 'Echando fuera la maldición de pobreza'),
  (9, 42, 'El perfecto amor echa fuera el temor'),
  (9, 43, 'El fuego de Su presencia'),
  (9, 44, 'Las cuatro dimensiones de la fe'),
  (9, 45, 'Los peligros de la falta de perdón'),
  (9, 46, 'El poder de una iglesia sobrenatural'),
  (9, 47, 'La fidelidad de Dios'),
  (9, 48, 'La perfecta voluntad de Dios'),
  (9, 49, 'El poder del yelmo de la salvación'),
  (9, 50, 'Entrando en un nuevo ciclo de bendición'),
  (9, 51, 'El verdadero significado de la Navidad'),
  (9, 52, 'Oración de salvación')
) AS t(libro_numero, numero, nombre) ON l.numero = t.libro_numero
WHERE l.fecha_eliminacion IS NULL
ON CONFLICT (libro_id, numero) WHERE iglesia_id IS NULL AND fecha_eliminacion IS NULL
  DO UPDATE SET nombre = EXCLUDED.nombre, orden = EXCLUDED.orden;
